#!/usr/bin/env bun
/**
 * Generate TypeScript types from Cairo contract ABIs using abi-wan-kanabi
 *
 * This script generates type-safe ABI constants that can be used with
 * starknet.js's contract.typedv2() for full TypeScript integration.
 *
 * Usage: bun run scripts/generate-types.ts
 *
 * Reference: https://starknetjs.com/docs/next/guides/contracts/abi_typescript/
 */

import { execSync } from 'child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

// Configuration
const CONTRACTS_DIR = join(__dirname, '../../..', 'contracts/target/dev');
const OUTPUT_DIR = join(__dirname, '../src/types/generated');

// Contract files to process (production contracts only)
const CONTRACTS = [
  // Core protocol contracts
  { file: 'horizon_Factory.contract_class.json', name: 'Factory' },
  { file: 'horizon_MarketFactory.contract_class.json', name: 'MarketFactory' },
  { file: 'horizon_Router.contract_class.json', name: 'Router' },
  { file: 'horizon_RouterStatic.contract_class.json', name: 'RouterStatic' },
  { file: 'horizon_Market.contract_class.json', name: 'Market' },
  // Token contracts
  { file: 'horizon_SY.contract_class.json', name: 'SY' },
  { file: 'horizon_SYWithRewards.contract_class.json', name: 'SYWithRewards' },
  { file: 'horizon_PT.contract_class.json', name: 'PT' },
  { file: 'horizon_YT.contract_class.json', name: 'YT' },
  // Oracle contracts
  { file: 'horizon_PragmaIndexOracle.contract_class.json', name: 'PragmaIndexOracle' },
  { file: 'horizon_PyLpOracle.contract_class.json', name: 'PyLpOracle' },
];

function main(): void {
  console.log('Generating TypeScript types from contract ABIs...\n');

  if (!existsSync(CONTRACTS_DIR)) {
    console.error(`Contracts directory not found: ${CONTRACTS_DIR}`);
    console.log('Make sure to build contracts first with: scarb build');
    process.exit(1);
  }

  // Create output directory
  if (!existsSync(OUTPUT_DIR)) {
    mkdirSync(OUTPUT_DIR, { recursive: true });
  }

  let processedCount = 0;
  // Store exports with module path for proper sorting
  const exportEntries: { modulePath: string; line: string }[] = [];

  for (const contract of CONTRACTS) {
    const inputPath = join(CONTRACTS_DIR, contract.file);

    if (!existsSync(inputPath)) {
      console.warn(`Contract file not found: ${contract.file}`);
      continue;
    }

    const outputPath = join(OUTPUT_DIR, `${contract.name}.ts`);

    try {
      console.log(`Processing: ${contract.name}`);

      // Use abi-wan-kanabi to generate types
      execSync(`npx abi-wan-kanabi --input "${inputPath}" --output "${outputPath}"`, {
        stdio: 'pipe',
      });

      // Read the generated file and rename the export
      const content = readFileSync(outputPath, 'utf-8');

      // abi-wan-kanabi generates: export const ABI = [...] as const;
      // We want to rename it to a specific name like FACTORY_ABI
      const abiName = `${contract.name.toUpperCase()}_ABI`;
      const updatedContent = content.replace(
        /export const ABI = /,
        `export const ${abiName} = `
      );

      writeFileSync(outputPath, updatedContent);

      exportEntries.push({
        modulePath: `./${contract.name}`,
        line: `export { ${abiName} } from './${contract.name}';`,
      });
      processedCount++;
    } catch (error) {
      console.error(`Error processing ${contract.file}:`, error);
    }
  }

  // Sort exports by module path (Biome's organizeImports sorts by import path)
  exportEntries.sort((a, b) => a.modulePath.localeCompare(b.modulePath));

  const indexContent = `/**
 * Auto-generated typed ABIs for Horizon Protocol contracts
 * Generated by: bun run codegen
 *
 * Usage with starknet.js:
 * \`\`\`typescript
 * import { Contract } from 'starknet';
 * import { ROUTER_ABI } from '@/types/generated';
 *
 * const router = new Contract(ROUTER_ABI, address, provider).typedv2(ROUTER_ABI);
 * // Now all calls are fully typed!
 * const [pt, yt] = await router.mint_py_from_sy(ytAddr, receiver, amountIn, minOut);
 * \`\`\`
 */

${exportEntries.map((e) => e.line).join('\n')}
`;

  writeFileSync(join(OUTPUT_DIR, 'index.ts'), indexContent);

  // Format generated files with Biome to ensure they pass lint checks
  console.log('\nFormatting generated files...');
  try {
    execSync(`npx biome check "${OUTPUT_DIR}" --write`, { stdio: 'pipe' });
  } catch {
    // biome check --write may exit with non-zero if it made fixes, which is fine
  }

  console.log(`\nGenerated types for ${String(processedCount)} contracts`);
  console.log(`Output: ${OUTPUT_DIR}`);

  // Fail if no contracts were processed - the frontend can't build without ABIs
  if (processedCount === 0) {
    console.error('\nNo contracts were processed. Build contracts first with: make build');
    process.exit(1);
  }
}

main();
