// Generated by apibara

declare module "apibara/types" {
  interface ApibaraRuntimeConfig {
   network: string,

   starknet: {
      startingBlock: number,

      streamUrl: string,
   },
  }
}
export type {};