name: Lint

on:
  push:
    branches: [main]
    paths: [contracts/**]
  pull_request:
    branches: [main]
    paths: [contracts/**]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: contracts
    steps:
      - uses: actions/checkout@v4

      - name: Setup Scarb
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.15.0"

      - name: Lint check
        run: scarb check
