name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Scarb
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.14.0"

      - name: Setup snfoundry
        uses: foundry-rs/setup-snfoundry@v3
        with:
          starknet-foundry-version: "0.54.0"

      - name: Run tests
        run: snforge test
